required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  name = "github.com/graph-gophers/dataloader"
  version = "5.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
